### ISSUE TITLE
New Light Effect: Formula 1 Racing Signal

### ISSUE THREAD

**Issue by michaelgale** [fx-bricks/pfx-brick-dev#1]

**Comment by michaelgale** [comment]
![Screen Shot 2019-04-17 at 10 05 26 PM](https://user-images.githubusercontent.com/2913880/56332409-42f9d480-615e-11e9-8cf6-308803229238.png)

**Comment by michaelgale** [comment]
Is the sequence of the lights as shown above?  Do the time/fade factor require adjustable parameters?

**Comment by AlexanderEhle** [comment]
"Small mistake in the picture. Green lights are on output 2 and yellow lights on 1" !

The picture shows the connection of LEDs with a LAB. All yellow and green LEDs are connected together to output 1 and 2 (rows). The red signals are connected to output 3 to 7 and each output drives two red signals at once.

There are different styles depending on the situation.

„Formula 1 - Start Training“: All green lights are on (Output 2)
„Formula 1 - Training break“: all yellow lights are on (Output 1)
"Formel 1 - Training end": all red Signals are on (Outputs 3,4,5,6,7)
„Formel 1 - Countdown Introduction": At first all red Signals are on and they switchin off from left to right
(3->4->5->6->7)
The turn off time of the signals are 15 min (Output 3), 5 Minutes (Output 4), 3 Minutes (Output 5), 1 Minute (Output 6) and 15 Sek (Output 7) in reality, so it would be good to have a setting fot the time (e.g. real time, average, fast) 
If the last red light is off (7) all green lights switches on (2). 

Here are graphics with the time-steps
https://www.formel1.de/inside/reglement/startprozedur

„Formula 1 - Countdown Start“: All red Singals are switching on from left to right (3->7) with a 1 Sec step size 0,2 to 3s after switching on the last red light (7), all lights goes off. (No Parameters)

„Formual 1 – break of race“: All red signals (3,4,5,6,7) are on at the same time and all yellow singals are flashing. Parametet perhaps are the blinking speed.

**Comment by AlexanderEhle** [comment]
![Formula1](https://user-images.githubusercontent.com/36688361/56340635-c2b18e80-61b2-11e9-80aa-ce696a7ce1ca.png)

**Comment by AlexanderEhle** [comment]
Pit Lane Signal
![Formula1_Box](https://user-images.githubusercontent.com/36688361/56471452-0f1af980-6453-11e9-80ad-cd914b7ad442.png)

Effects
"Formula1 – Pit Lane closed“ (The red signals are on, output 1)
„Formula1 – Pit Lane open“ (The green signal is on, output 2)
„Formula1 – Pit Lane open + Warning“ (The green and all blue signals are on, output 3)

**Comment by michaelgale** [comment]
Is this graphic also correct?  It looks like the countdown sequence is in the opposite direction (right to left)?
![start_countdown](https://user-images.githubusercontent.com/2913880/56925095-8593a900-6a9c-11e9-9c09-e780977ee8b7.gif)

**Comment by AlexanderEhle** [comment]
Yes, I simplify the red lights to one output. The graphic from you is starting from bottom. In the book they starts from top,

Countdown to the formation lap
![grafik](https://user-images.githubusercontent.com/36688361/56939720-4734d300-6b0a-11e9-84d2-5d193d084b1b.png)

Countdown to start
![grafik](https://user-images.githubusercontent.com/36688361/56939729-4e5be100-6b0a-11e9-8fbd-fa863152af17.png)
