### ISSUE TITLE
New Light Effect: Dragster Starter Signal

### ISSUE THREAD

**Issue by michaelgale** [fx-bricks/pfx-brick-dev#2]

**Comment by michaelgale** [comment]
![Screen Shot 2019-04-17 at 10 05 51 PM](https://user-images.githubusercontent.com/2913880/56332403-3a090300-615e-11e9-8119-906057046c7e.png)

**Comment by michaelgale** [comment]
How does this sequence work?  Is it in the order of the numbers above? 
Does the timing require a parameter, e.g. slow, fast etc.?
Do the lights require fade and/or adjustable fade?

**Comment by AlexanderEhle** [comment]
The upper area  contains four orange LEDs for preparation signal. They are switching like the following sequence. In reality the lights depends on distance measurments of the cars. Time-Setting or speed for each step would be fine to simulate the behaviour.

![DragsterSequenceOrange](https://user-images.githubusercontent.com/36688361/56340802-57b48780-61b3-11e9-84fd-9d227bf31bae.png)

The yellow signals are for the count-down and switching from top to bottom like shown in the next sequence. If the last yellow light is on, the green follows after 0,5 seconds (Standard). The Professional modes shows all yellow lights at once and after 0,5s or 0,4s the green light is activated.

![DragsterCountDown](https://user-images.githubusercontent.com/36688361/56340845-787cdd00-61b3-11e9-9c79-690161c3bb8f.png)

Suggested modes:
Dragster „Professional 0.4“ (0,4 Sek for green after yellow)
Dragster „Professional 0.5“ (0,5 Sek for green after yellow)
Dragster „Standard“ (0,5 Sek for green after yellow count down)
Perhaps a "Dragster Play" Mode with different speed settings could be helpful to show scenes on MOCs.
