### ISSUE TITLE
New Light Effect: Airport Runway Lights

### ISSUE THREAD

**Issue by michaelgale** [fx-bricks/pfx-brick-dev#3]

**Comment by michaelgale** [comment]
![Screen Shot 2019-04-17 at 10 07 27 PM](https://user-images.githubusercontent.com/2913880/56332391-2e1d4100-615e-11e9-88f3-6e24b629c8d9.png)

**Comment by michaelgale** [comment]
![Screen Shot 2019-04-17 at 10 07 45 PM](https://user-images.githubusercontent.com/2913880/56332432-54db7780-615e-11e9-9e93-8c3a29e7b72e.png)

**Comment by AlexanderEhle** [comment]
![RunwaySequenceArrow](https://user-images.githubusercontent.com/36688361/56341112-533c9e80-61b4-11e9-8dba-7b807a71a50f.png)

The arrow lights have a medium light and from 2 to 7 the lights flashes up with maximum light one after each other. On the end the output 8 flashes one time and the sequece starts again over and over. Speed of the sequence and perhaps the brightness of the lights (non flashing) and the flashing brightness.
fade factor would be helpful to adjust the effect.

**Comment by AlexanderEhle** [comment]
The Papi(s) needs two-color-leds (red/white). Parameter is the brightness of red or white. 

Papis higher: Switching each step by control from right to left from red to white
Papis lower: Switching each step by control from left to right from white to red
Initial start is 1/2 = red and 3/4 white. If we use the new pinlab, the outputs must adjusted
LED1white = 1, LED1red = 2
LED2white = 3, LED2red = 4
LED3white = 5, LED3red = 6
LED4white = 7, LED4red = 8
