### ISSUE TITLE
Support scripting actions with script files on the brick file system

### ISSUE THREAD

**Issue by michaelgale** [fx-bricks/pfx-brick-dev#9]
A feature often requested is the ability to script multiple actions in sequence.  This would indeed be a very useful feature.  The concept of how this could work is as follows:

1. Scripts would be human readable text files stored in the PFx Brick file system
2. Script syntax will be simple, easy to parse and human readable.
3. Scripts will normally execute in a linear sequence and terminate at the end or repeat.
4. Only one script can execute at a time.  A new script execution request will terminate a script in process.
5. Scripts will be executed by an action with the COMMAND byte set to a new command nemonic RUN_SCRIPT and the script file ID in another TBD byte.
6. Scripts will support the following actions:
  - set motor channel operation: set speed, stop, direction, etc.
  - set light channel behaviour: on, off, brightness
  - audio playback: start, stop
  - execution of any stored actions indexed by event ID (e.g. do action for left button speed remote channel 3)
  - time delay / wait
7. Script files can be copied to the PFx Brick using either the PFx App (new version required) or  by using a python script documented in the pfx-brick-py software API.

**Comment by AlexanderEhle** [comment]
Delay means how long activate the effect? E.g. 
Step 1: Light output 1 & 2 on for 0,5s, 
wait 0,5s 
Step 2: Light output 3 & 4 on for 0,5s, 
wait 0,5s 
then loop (restart with Step 1).

**Comment by AlexanderEhle** [comment]
I think the most of that signals in the attached pdf can be created by scripting. Give a sequence a name to identify it.

Feature: Import/Export for exchange would be nice for the community.

[RailwaySignals_Collection.pdf](https://github.com/fx-bricks/pfx-brick-dev/files/3102319/RailwaySignals_Collection.pdf)

**Comment by michaelgale** [comment]
Time delay / wait are the same thing.  There would be a script command which will simply wait for a specified time interval.  It will be complicated to also add a "run time" for a command.
Your example could be implemented like this:
LIGHT 1,2 ON
DELAY 0.5
LIGHT 1,2 OFF
LIGHT 3,4 ON
DELAY 0.5
LIGHT 3,4 OFF
REPEAT
